FUNCTION (JDEROBOT_ADD_LIBRARY)
	list(GET ARGN 0 CURR_LIB_NAME)
	list(GET ARGN 1 CURR_LIB_TYPE)

	IF (${CURR_LIB_NAME} IN_LIST JDEROBOT_ACTIVE_TARGETS)
	ELSE()
		set(JDEROBOT_ACTIVE_TARGETS_ ${JDEROBOT_ACTIVE_TARGETS} ${CURR_LIB_NAME})
		list(REMOVE_DUPLICATES JDEROBOT_ACTIVE_TARGETS_)
		set(JDEROBOT_ACTIVE_TARGETS ${JDEROBOT_ACTIVE_TARGETS_} CACHE INTERNAL "List of active targets" )
		set(${CURR_LIB_NAME}_TYPE ${CURR_LIB_TYPE} CACHE INTERNAL "Status of active targets" )
	ENDIF()

	add_library(${ARGN})
ENDFUNCTION(JDEROBOT_ADD_LIBRARY)



FUNCTION (JDEROBOT_RENAME_GENERATED_LIB TARGET_NAME OUTPUT_NAME)
	set_target_properties(${TARGET_NAME} PROPERTIES OUTPUT_NAME ${OUTPUT_NAME})
	set(${TARGET_NAME}_RENAMED ${OUTPUT_NAME}  CACHE INTERNAL "Renamed definition")
ENDFUNCTION()



FUNCTION(PRINT_TARGETS)
	MESSAGE("ACTIVE TARGETS:")
	FOREACH( TARGET ${JDEROBOT_ACTIVE_TARGETS})
		string(COMPARE EQUAL "${${TARGET}_TYPE}" "SHARED" _cmp)
		IF (_cmp)
			SET(temp_subix .so)
		ELSE()
			SET(temp_subix .a)
		ENDIF()
		IF (DEFINED ${TARGET}_RENAMED)
			SET(TARGET_FINAL ${${TARGET}_RENAMED})
		ELSE()
			SET(TARGET_FINAL ${TARGET})
		ENDIF()

		MESSAGE("${TARGET} -> ${${TARGET}_TYPE} -> ${TARGET_FINAL}${temp_subix}")

	ENDFOREACH()
ENDFUNCTION()



FUNCTION (JDEROBOT_GENERATE_INSTALL_FILES_BY_TARGET)
	UNSET(JDEROBOT_LIBS_NAMES_TO_INSTALL CACHE)
	FOREACH( TARGET ${JDEROBOT_ACTIVE_TARGETS})
		string(COMPARE EQUAL "${${TARGET}_TYPE}" "SHARED" _cmp)
		IF (_cmp)
			SET(temp_subix .so)
		ELSE()
			SET(temp_subix .a)
		ENDIF()
		IF (DEFINED ${TARGET}_RENAMED)
			SET(TARGET_FINAL ${${TARGET}_RENAMED})
		ELSE()
			SET(TARGET_FINAL ${TARGET})
		ENDIF()

		LIST(APPEND JDEROBOT_LIBS_NAMES_TO_INSTALL ${TARGET_FINAL}${temp_subix})
	ENDFOREACH()

	set(JDEROBOT_LIBS_NAMES_TO_INSTALL ${JDEROBOT_LIBS_NAMES_TO_INSTALL} CACHE INTERNAL "Generated files to install" )


ENDFUNCTION()



MACRO(JDEROBOT_DEPENDENT_OPTION option doc default depends force)
  IF(${option}_ISSET MATCHES "^${option}_ISSET$")
    SET(${option}_AVAILABLE 0)
    FOREACH(d ${depends})
      STRING(REGEX REPLACE " +" ";" CMAKE_DEPENDENT_OPTION_DEP "${d}")
      IF(${CMAKE_DEPENDENT_OPTION_DEP})
         SET(${option}_AVAILABLE 1)
      ELSE(${CMAKE_DEPENDENT_OPTION_DEP})
      ENDIF(${CMAKE_DEPENDENT_OPTION_DEP})
    ENDFOREACH(d)
    IF(${option}_AVAILABLE)
      OPTION(${option} "${doc}" "${default}")
      SET(${option} "${${option}}" CACHE BOOL "${doc}" FORCE)
    ELSE(${option}_AVAILABLE)
      IF(${option} MATCHES "^${option}$")
      ELSE(${option} MATCHES "^${option}$")
        SET(${option} "${${option}}" CACHE INTERNAL "${doc}")
      ENDIF(${option} MATCHES "^${option}$")
      SET(${option} ${force})
    ENDIF(${option}_AVAILABLE)
  ELSE(${option}_ISSET MATCHES "^${option}_ISSET$")
    SET(${option} "${${option}_ISSET}")
  ENDIF(${option}_ISSET MATCHES "^${option}_ISSET$")
ENDMACRO(JDEROBOT_DEPENDENT_OPTION)

